### ISSUE TITLE
Implement phase 1 of proposal (PoC)

### ISSUE THREAD

**Issue by imiric** [grafana/k6#3038]

**Comment by saniyar-dev** [comment]
Hi.
I assume that new-http api is not in default k6 binary.
How can I build/download a proper binary which includes this api?

**Comment by oleiade** [comment]
The maintainers' team agreed upon the following concrete plan to move forward with the implementation of the new HTTP module's phase 1 (as specified in the [design document](https://github.com/grafana/k6/blob/master/docs/design/018-new-http-api.md#phase-1-create-initial-k6-extension)):


```[tasklist]
### Tasks
- [ ] Begin with the [implementation of the Streams API](https://github.com/grafana/k6/issues/2978).
- [ ] Agree upon most minimal scope for the new HTTP module's client API implementation, as per [design document](https://github.com/grafana/k6/blob/master/docs/design/018-new-http-api.md#phase-1-create-initial-k6-extension).
- [ ] Implement 👆scope, with a focus on enabling the use of large binary files, leveraging the [Streams API](https://github.com/grafana/k6/issues/2978), and likely providing a native implementation of `FileData`
```

Specifically out of scope for phase 1:
The maintainers reached an agreement, that support for TCP, DNS, etc should be delegated to a future phase.

**Comment by saniyar-dev** [comment]
Hi, everyone. I'm currently working on this issue by implementing the phase 1 of this new HTTP API in [this repo](https://github.com/saniyar-dev/xk6-new-http), in form of an k6 extension. i worked hours on it, still need to implement lots of features to it. I would be very thankful to anyone who wants to share their insights on it with me.
Also i know that it needs a lot of progress to be a candidate for a standard implementation of phase 1 for the new HTTP API, but can anyone share any roadmap, etc. to help me find my way through it? Any contact point to reach and talk with the team would be great too!
I'm getting confused as there is lots of open issues with this label however i read lots of them and i think i can implement all.

**Comment by oleiade** [comment]
Closing this as the project direction evolved. Feel free to reopen in the future if relevant.
