### ISSUE TITLE
k6 REST API v2

### ISSUE THREAD

**Issue by olegbespalov** [grafana/k6#3497]
# What?

Our current version of the REST API hasn't been touched for a long time. At some point we'd like to improve it (a better API design, remove unnecessary dependencies, etc) and took into account the latest state like distributed execution.

For now this is blocked by the #140

```[tasklist]
### Tasks
- [ ] Suggest a API proposal (design doc) for the v2
- [ ] https://github.com/grafana/k6/issues/995
- [ ] https://github.com/grafana/k6/issues/3239
```

# Why?

We believe that the current API could be better.

**Comment by codebien** [comment]
In https://github.com/grafana/k6/issues/3583 discussion, we set the hypothesis that k6 doesn't need a _real_ HTTP API v2 after we have implemented native distributed execution. Most of the current endpoints cover use cases useful before #1007 or the absence of the native distribution execution.

So, potentially, v2 means only to drop the endpoints from `v1` that could be useless after we have introduced native distributed execution. As we don't have specific endpoints that we are considering to add.

Still, it remains all the work required in terms of refactoring. But it may not strictly require the bump of the version.
