### ISSUE TITLE
Make ReadableStream (WIP) implementation pass WPT test suite

### ISSUE THREAD

**Issue by oleiade** [grafana/k6#3659]
As we have a starting ReadableStream implementation, we aim to pass the relevant [Web Platform Test](https://github.com/web-platform-tests/wpt) suite's relevant tests.

```[tasklist]
### Tasks
- [x] Pass [bad-strategies.any.js](https://github.com/web-platform-tests/wpt/blob/master/streams/readable-streams/bad-strategies.any.js)
- [x] Pass [bad-underlying-sources.any.js](https://github.com/web-platform-tests/wpt/blob/master/streams/readable-streams/bad-underlying-sources.any.js)
- [x] Pass [cancel.any.js](https://github.com/web-platform-tests/wpt/blob/master/streams/readable-streams/cancel.any.js)
- [x] Pass [constructor.any.js](https://github.com/web-platform-tests/wpt/blob/master/streams/readable-streams/constructor.any.js)
- [x] Pass [count-queuing-strategy-integration.any.js](https://github.com/web-platform-tests/wpt/blob/master/streams/readable-streams/count-queuing-strategy-integration.any.js)
- [x] Pass [default-reader.any.js](https://github.com/web-platform-tests/wpt/blob/master/streams/readable-streams/default-reader.any.js)
- [x] Pass [floating-point-total-queue-size.any.js](https://github.com/web-platform-tests/wpt/blob/master/streams/readable-streams/floating-point-total-queue-size.any.js)
- [x] Pass [general.any.js](https://github.com/web-platform-tests/wpt/blob/master/streams/readable-streams/general.any.js)
- [ ] Pass [patched-global.any.js](https://github.com/web-platform-tests/wpt/blob/master/streams/readable-streams/patched-global.any.js)
- [x] Pass [reentrant-strategies.any.js](https://github.com/web-platform-tests/wpt/blob/master/streams/readable-streams/reentrant-strategies.any.js)
- [ ] Pass [tee.any.js](https://github.com/web-platform-tests/wpt/blob/master/streams/readable-streams/tee.any.js)
- [x] Pass [templated.any.js](https://github.com/web-platform-tests/wpt/blob/master/streams/readable-streams/templated.any.js)
```

**Comment by joanlopez** [comment]
**Status update (17/04)**
- General: _25 out of 38 pass_
- Patched global: _Should we discard it?_
- Reentrant strategies: _3 fail => 1 (`tee`), 1 (`pipeTo`), 1 (flaky)_
- Tee: _Should we discard it?_

_All the other test suites (bad strategies, bad underlying sources, cancel, ..., templated) work as expected!_ 🎉 

Other stuff pending: _revisit [ReadableByteStreams](https://github.com/web-platform-tests/wpt/tree/master/streams/readable-byte-streams)?_

**Comment by oleiade** [comment]
In the context of this specific issue, we agreed to dismiss the `patched-global` test suite as we judge it irrelevant to our use case, and we decide to explicitly not implement and test the `tee` feature of streams.
