### ISSUE TITLE
Configurable download behavior

### ISSUE THREAD

**Issue by inancgumus** [grafana/k6#4197]
### What?

Add support to make download behavior configurable:
- Downloading can be turned on or off.
- Downloads are turned on by default in local runs.
- Downloads are turned off in remote runs for security reasons.
- User can set where to download files.
- Create temporary directories if the download path is unset.

### Why?

Turning off is required because some scripts hang when the file choosers open.

Turning on is required when users want to download files and see where the files are.

#### Turning On and Off Downloads

We can control the download behavior using the existing `BrowserContext.acceptDownloads` option:

```javascript
const context = await browser.newContext({
    acceptDownloads: false,
});
```

However, although we have the option implemented (set to `false` by default), we don't use it in the module code. So, the module's current behavior is always to accept downloads and open file choosers. 

The goal of this issue is to use this option to control download behavior.

Other tools set this option to `true` by default. One advantage of keeping it `false` is that it lets us learn about user behavior. The disadvantage is that users would need to explicitly set it to `true` to make downloading in their scripts work. We'll set the option to `true` by default to match the general industry.

#### Setting the download path

We can let users where to save files using the `downloadsPath` option:

```javascript
const context = await browser.newContext({
    acceptDownloads: true,
    downloadsPath: '/my/directory',
});
```

When set, files are downloaded into the directory. Otherwise, they're saved in a temporary directory.

### CDP API

```go
action := cdpbrowser.
	SetDownloadBehavior(/* configurable */).
	WithDownloadPath(/* configurable */).
	WithBrowserContextID(...)
```

Explanation:

* `SetDownloadBehaviorBehaviorDefault`: Opens a file chooser by default. This is the browser module's current behavior even without calling `SetDownloadBehavior`.
* `SetDownloadBehaviorBehaviorAllow`: Automatically downloads files to a user-specified folder. Other tools randomly pick a directory name if not specified. We'll follow suit.
* `SetDownloadBehaviorBehaviorDeny`: Denies downloads. We'll set this based on the user's request or if the test run is on the cloud.

### Tasks

```[tasklist]
### Tasks
- [ ] grafana/xk6-browser#1496
- [ ] PR: Add `acceptDownloads` to `newContext` and `newPage`
- [ ] PR: Set `acceptDownloads` to `true` by default
- [ ] PR: Activate `acceptDownloads` CDP calls
- [ ] PR: Turn off `acceptDownloads` for remote runs
- [ ] Add a JavaScript example
- [ ] Docs PR
- [ ] Update the k6 release notes for each PR and tasks
```

### Related PR(s)/Issue(s)

grafana/xk6-browser#98

**Comment by efuturetoday** [comment]
@inancgumus FYI: I created a PR related to this issue: https://github.com/grafana/k6/pull/5752

**Comment by inancgumus** [comment]
Hi @efuturetoday, thanks a lot! Does your PR support _"Downloads are turned off in remote runs for security reasons"_? Also, other features mentioned in the issue description?

**Comment by efuturetoday** [comment]
@inancgumus Yes I followed the specification outlined here in this topic. Also note #5753 based on this change and implementing the `download` page event
