### ISSUE TITLE
Move Sobek entirely out of the business logic

### ISSUE THREAD

**Issue by inancgumus** [grafana/k6#4219]
### What?

Move Sobek entirely out of the business logic.

### Why?

* Prevent Sobek data races.
* Better type-safety using native Go constructs.
* Developer productivity increase.
* Separation of concerns.
* Moving Sobek handling to the mapping layer will make the code easy to reason about, reduce the business logic's Sobek dependency, and simplify the business logic code and tests.
* Having Sobek in the business logic requires constant encoding and decoding.

### Desobekifying Sobek transformation

Besides moving the calling of Sobek option parsing in the business logic, we also plan to move the Sobek-dependent option parsing part out of the business logic. Once we finish doing the same with the rest of the option parsing, we can entirely remove the Sobek dependency from the business logic.

We currently parse Sobek values into our business logic types, but the parsing dependency is in an unrelated package (common). To enhance maintainability, we move the parsing process and keep related components together (in the mapping layer). Additionally, we could implement a `Validate` method for the business types (in the common package) to check their validity separately from the Sobek transformation.

Moreover, we use pointers quite liberally, which is not good in terms of reduced performance and also because of many nil-pointer panics. Also, since our module is highly current, it's dangerous to have so many pointers around. So, another goal would be to get rid of as many pointer-ed options as possible to boost stability even more.

See grafana/xk6-browser#1510 for an example.

### Tasks

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/xk6-browser/issues/1272
- [ ] https://github.com/grafana/xk6-browser/issues/1271
- [ ] https://github.com/grafana/xk6-browser/issues/1273
- [ ] https://github.com/grafana/xk6-browser/issues/1274
- [ ] https://github.com/grafana/xk6-browser/issues/1525
- [ ] https://github.com/grafana/xk6-browser/issues/1270
- [ ] https://github.com/grafana/xk6-browser/issues/1282
- [ ] https://github.com/grafana/xk6-browser/issues/1522
- [ ] grafana/xk6-browser#1393
- [ ] https://github.com/grafana/xk6-browser/issues/1269
- [ ] https://github.com/grafana/xk6-browser/issues/1275
- [ ] https://github.com/grafana/xk6-browser/issues/1277
- [ ] https://github.com/grafana/xk6-browser/issues/1281
- [ ] https://github.com/grafana/xk6-browser/pull/1228
- [ ] https://github.com/grafana/xk6-browser/pull/1198
```

### Related PR(s)/Issue(s)

grafana/xk6-browser#271

**Comment by ankur22** [comment]
@inancgumus i think we should close this now. Sobek isn't used in the classes that are referenced in this issue, at least not in the type files themselves e.g. `page.go`, `locator.go`, etc

The moving of parsing logic into browser or a new package should be dealt with in another issue as it relates to more cleanup then functionality.

**Comment by inancgumus** [comment]
This will continue in #5305.
