### ISSUE TITLE
Improve screenshot saving and uploading

### ISSUE THREAD

**Issue by inancgumus** [grafana/k6#4229]
This is a grand issue for keeping track of screenshot functionality.

```[tasklist]
### Tasks
- [ ] grafana/k6#4129
- [ ] grafana/xk6-browser#1342 
- [ ] grafana/xk6-browser#1339 
- [ ] grafana/xk6-browser#922
- [ ] grafana/k6#4202
- [ ] grafana/xk6-browser#785
```
