### ISSUE TITLE
Implement `Download` handling

### ISSUE THREAD

**Issue by robingustafsson** [grafana/k6#4233]
### What?

Add support for `Download`, handling of file downloads in the browser.

### Why?

Allow users to manage file downloads.

### How?

- Playwright docs: https://playwright.dev/docs/api/class-download
- https://playwright.dev/docs/api/class-page#page-event-download

### Tasks

```[tasklist]
### Tasks
- [ ] Research: `page.on` generalization
- [ ] https://github.com/grafana/k6/issues/4197
- [ ] TODO: Add the remaining `Download` methods
```
