### ISSUE TITLE
Non-iterational goroutines should not abort an iteration

### ISSUE THREAD

**Issue by inancgumus** [grafana/k6#4403]
### Brief summary

Goroutines other than the one that drives an iteration should not panic. Otherwise, k6 won't catch the panic and fail.

We should take control of our non-iteration goroutines: Not panic and cause an iteration to be prematurely aborted.

More details about how to craft a solution:
* https://github.com/grafana/k6/pull/2453
* https://github.com/grafana/k6/blob/d81bb4162517064bdaf9b23bc15062e08184757d/js/runner.go#L788-L793
* https://github.com/grafana/k6/blob/d81bb4162517064bdaf9b23bc15062e08184757d/js/bundle.go#L334-L348

### xk6-browser version

v0.7.0

### OS

Staging Cloud

### Docker version and image (if applicable)

grafana/k6-cloud-scripts-to-archive:2.40.6-xk6browser-v0.7.0-1

### Steps to reproduce the problem

Pawel ran the following script, and we got sentry alerts because of the panics.

<details>
<summary>This script panics.</summary>

```javascript
import { check, sleep } from 'k6';
import { Counter } from 'k6/metrics';
import { chromium } from 'k6/x/browser';


const checkpoint1 = new Counter('checkpoint1');
const checkpoint2 = new Counter('checkpoint2');
const checkpoint3 = new Counter('checkpoint3');
const checkpoint4 = new Counter('checkpoint4');
const checkpoint5 = new Counter('checkpoint5');
const checkpoint6 = new Counter('checkpoint6');
const checkpoint7 = new Counter('checkpoint7');


export let options = {
  vus: 100,
  duration: '10h',
}

export function setup(){
  console.log("Running setup")
}

export default function () {
  const browser = chromium.launch({
    headless: true
  });
  const context = browser.newContext();
  const page = context.newPage();

  checkpoint1.add(1);

  // Goto front page, find login link and click it
  page.goto('https://test.k6.io/', { waitUntil: 'networkidle' });

  checkpoint2.add(1);

  Promise.all([
    page.waitForNavigation(),
    page.locator('a[href="/my_messages.php"]').click(),
  ]).then(() => {
    checkpoint3.add(1)

    // Enter login credentials and login
    page.locator('input[name="login"]').type('admin');
    page.locator('input[name="password"]').type('123');
    // We expect the form submission to trigger a navigation, so to prevent a
    // race condition, setup a waiter concurrently while waiting for the click
    // to resolve.

    checkpoint4.add(1)

    return Promise.all([
      page.waitForNavigation(),
      page.locator('input[type="submit"]').click(),
    ]);
  }).then(() => {
    checkpoint5.add(1)

    check(page, {
      'header': page.locator('h2').textContent() == 'Welcome, admin!',
    });
  }).finally(() => {
    checkpoint6.add(1)
    page.close();
    browser.close();
    checkpoint7.add(1)
  });
  sleep(1);
}

export function teardown() {
  console.log("Running teardown")
}
```

</details>

The script has an incorrect usage of promises, and the fix is easy:

```javascript
page.goto('https://test.k6.io/', { waitUntil: 'networkidle' });

// this should be page.goto(...).then(...)
```

However, the problem is deeper than it seems.

See more details in the test run: 1620122 (proxy).

### Actual behaviour

Panic causes an iteration to be prematurely aborted.

```[tasklist]
### Tasks
- [ ] Don't panic in `Response`
- [ ] Don't panic in `JSHandle`
- [ ] Don't panic in `ElementHandle`
- [ ] Don't panic in `Frame`
- [ ] Don't panic in `Page`
- [ ] Don't panic in `Worker`
- [ ] Don't panic in `BrowserContext`
- [ ] Don't panic in `Browser`
- [ ] Don't panic in `BrowserType`
- [ ] TBA: Look at the remaining panics and split them up again into smaller tasks.
- [ ] Move `k6ext.Panic` into the mapping layer.
- [ ] Move `k6ext.Promise` into the mapping layer and incorporate `panicIfInternalError` in it.
```

**Comment by ankur22** [comment]
I'm closing this since i've not seen such errors after the vast amount of work on refactoring code. There's a chance that this may reoccur, but it might be best to focus on the exact problem when it does arise. Please reopen if you disagree.
