### ISSUE TITLE
Refactor timeout zero methods in Page/Frame/ElementHandle

### ISSUE THREAD

**Issue by inancgumus** [grafana/k6#4449]
Please read [the comment](https://github.com/grafana/xk6-browser/pull/369#discussion_r890011938) for details.

Some of the behavior we witnessed for refactoring the zero timeouts:

- [ ] grafana/xk6-browser#369
- [ ] grafana/xk6-browser#372
- [ ] grafana/xk6-browser#373
- [ ] grafana/xk6-browser#347
- [ ] grafana/xk6-browser#376
- [ ] grafana/xk6-browser#377

**Comment by AgnesToulet** [comment]
Seems done.
