### ISSUE TITLE
Linter issues

### ISSUE THREAD

**Issue by imiric** [grafana/k6#4496]
Closing this issue should be done when all existing issues are fixed and we remove `--new-from-rev` from the CI job.

**TODO:**

- [x] grafana/xk6-browser#211
- [x] Reenable the new-from-rev option: grafana/xk6-browser#220
- [x] Set a list of linters and fix some: grafana/xk6-browser#216
- [x] grafana/xk6-browser#245 
- [x] Fix linter errs and grafana/xk6-browser#246
- [ ] Properly fix and remove all `nolint` directives
- [ ] cyclop
- [ ] deadcode
- [ ] dogsled
- [ ] dupl
- [ ] durationcheck
- [ ] errcheck
- [ ] errchkjson
- [ ] errname
- [ ] errorlint
- [ ] exhaustive
- [ ] exportloopref
- [ ] forbidigo
- [x] forcetypeassert: grafana/xk6-browser#425
- [ ] funlen
- [ ] gci
- [ ] gochecknoglobals
- [ ] gocognit
- [ ] goconst
- [ ] gocritic
- [ ] godot
- [ ] gofmt
- [ ] gofumpt
- [ ] goimports
- [ ] gosec
- [ ] gosimple
- [ ] govet
- [ ] ifshort
- [ ] importas
- [ ] ineffassign
- [ ] lll
- [ ] makezero
- [ ] misspell
- [ ] nakedret
- [ ] nestif
- [ ] nilerr
- [ ] nilnil
- [ ] nlreturn
- [ ] nolintlint
- [ ] prealloc
- [ ] predeclared
- [ ] revive
- [ ] staticcheck
- [ ] structcheck
- [ ] tagliatelle
- [ ] thelper
- [ ] tparallel
- [ ] typecheck
- [ ] unconvert
- [ ] unparam
- [ ] unused
- [ ] varcheck
- [ ] wastedassign
- [ ] whitespace
- [ ] wrapcheck

**Comment by mstoykov** [comment]
This has mostly been done and I guess the remaining work is in #4107
